[build]
  command = "rm -rf node_modules && npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_YARN = "false"
  NPM_CONFIG_PACKAGE_LOCK = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ] 